variable "lambda_zip_path" {}
variable "function_name" {}
variable "lambda_role_name" {}
variable "events_queue_name" {}
variable "processor_function_name" {}
variable "parquet_processor_function_name" {}
variable "processor_zip_path" {}
variable "parquet_processor_zip_path" {}
variable "data_lake_bucket_name" {}